apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: search
    component: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search
      component: rabbitmq
  template:
    metadata:
      name: rabbitmq
      labels:
        app: search
        component: rabbitmq
    spec:
      containers:
      - image: bitnami/rabbitmq
        name: rabbitmq
        env:
        - name: RABBITMQ_USERNAME
          value: crawler
        - name: RABBITMQ_PASSWORD
          value: crawler_password
