---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  labels:
    app: ui-service
    component: ui
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ui-service
      component: ui
  template:
    metadata:
      name: ui-pod
      labels:
        app: ui-service
        component: ui
    spec:
      containers:
      - image: podstolniy/ui:0.0.1
        name: ui
        env:
        - name: MONGO
          value: mongodb
        - name: MONGO_PORT
          value: "27017"
