---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-prog
  labels:
    app: prometheus
    component: prometheus-prog
spec:
  type: NodePort
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: prometheus
    component: prometheus-prog

