---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-prog
  labels:
    app: search_engine
    component: prometheus-prog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search_engine
      component: prometheus-prog
  template:
    metadata:
      name: fluentd
      labels:
        app: search_engine
        component: prometheus-prog
    spec:
      containers:
      - image: podstolniy/prometheus-prog:0.0.1
        name: fluentd
        env:
        - name: ENV
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace

