version: '3'
services:
  crawler_db:
    image: mongo:3.2
    volumes:
      - crawler_db:/data/db
    networks:
      back_net:
        aliases:
          - crawler_db
          - mongo_db
    environment: 
      - ZIPKIN_ENABLED=true

  rabbitmq:
    image: rabbitmq:3-management-alpine
    depends_on:
      - crawler_db
    volumes:
      - rabbit:/var
    networks:
      - back_net
    environment: 
      - ZIPKIN_ENABLED=true

  ui:
    image: podstolniy/ui:0.0.1
    depends_on:
      - crawler_db
    ports:
      - 8000:8000/tcp
    networks:
      - back_net
    environment: 
      - ZIPKIN_ENABLED=true

  crawler:
    image: podstolniy/crawler:0.0.1
    restart: always
    depends_on:
      - crawler_db
      - rabbitmq
    networks:
      - back_net
    environment: 
      - ZIPKIN_ENABLED=true

  prometheus:
    image: podstolniy/prometheus-prog:0.0.1
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      - back_net

  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - back_net

  mongodb-exporter:
    image: percona/mongodb_exporter:0.30.0
    command:
      - '--mongodb.uri=mongodb://mongo_db:27017'
    networks:
      - back_net

volumes:
  crawler_db:
  rabbit:
  prometheus_data:

networks:
  back_net:
