---
apiVersion: v1
kind: Service
metadata:
  name: ui-crawler-service
  labels:
    app: crawler
    component: ui-crawler-service
spec:
  type: ClusterIP
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: ui-crawler-service
    component: crawler
