---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-crawler
  labels:
    app: crawler
    component: ui-crawler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crawler
      component: ui-crawler
  template:
    metadata:
      name: crawler-pod
      labels:
        app: crawler
        component: ui-crawler
    spec:
      containers:
      - image: podstolniy/crawler:0.0.1
        name: ui-crawler
        env:
        env:
        - name: MONGO
          value: mongo
        - name: MONGO_PORT
          value: "27017"
        #- name: MONGO
        #  value: mongodb
        #- name: MONGO_PORT
        #  value: "27017"
        #- name: RMQ_HOST
        #  value: rabbitmq
        #- name: RMQ_QUEUE
        #  value: queue
        #- name: RMQ_USERNAME
        #  value: crawler
        #- name: RMQ_PASSWORD
        #  value: crawler_password
        #- name: CHECK_INTERVAL
        #  value: "5"
        #- name: EXCLUDE_URLS
        #  value: '.*github.com'
